### ISSUE TITLE
RuntimeError: Error compiling objects for extension

### ISSUE THREAD

**Issue by ShenZheng2000** [lhoyer/MIC#25]
I am using PyTorch 1.9.0 and CUDA 11.1, which should be similar to the requirement (PyTorch 1.12.0 and CUDA 11.3).

However, when I run `python setup.py build develop`, I get the following error:

```
The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "setup.py", line 59, in <module>
    setup(
  File "/root/miniconda3/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/root/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda3/lib/python3.8/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/root/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/root/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/root/miniconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 79, in run
    _build_ext.run(self)
  File "/root/miniconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "/root/miniconda3/lib/python3.8/distutils/command/build_ext.py", line 340, in run
    self.build_extensions()
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 709, in build_extensions
    build_ext.build_extensions(self)
  File "/root/miniconda3/lib/python3.8/site-packages/Cython/Distutils/old_build_ext.py", line 195, in build_extensions
    _build_ext.build_ext.build_extensions(self)
  File "/root/miniconda3/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
    self._build_extensions_serial()
  File "/root/miniconda3/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
    self.build_extension(ext)
  File "/root/miniconda3/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "/root/miniconda3/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
    objects = self.compiler.compile(sources,
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 530, in unix_wrap_ninja_compile
    _write_ninja_file_and_compile_objects(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1355, in _write_ninja_file_and_compile_objects
    _run_ninja_build(
  File "/root/miniconda3/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1682, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error compiling objects for extension
```

I'm uncertain if this installation problem is caused by a mismatched torch and cuda version because I couldn't find any hard constraints for the code related to torch and cuda versions.

**Comment by krumo** [comment]
Hi, thank you for your interest in our work. The log suggests that the customized cuda operators are not compiled successfully. The detection branch is developed on deprecated maskrcnn-benchmark, which is based on old PyTorch 1.0 nightly. As the PyTorch CUDA API changes, I made several modifications to these cuda files so that they are compatible with PyTorch 1.12.0 and CUDA 11.3. So the performance on other environment settings is untested and unpromised. Thus, my suggestion would be to set up a new environment according to the instructions in det/README.md.
