### ISSUE TITLE
question about run the code twice, occour ModuleNotFoundError: No module named 'torch._six'

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/MIC#50]
When I run the code python 
```python
run_experiments.py --config configs/mic/gtaHR2csHR_mic_hrda.py first time.
```
 It success run and here the result;
```txt
n a future version of Python.
  mem_mb = torch.tensor([mem / (1024 * 1024)],
2023-06-19 01:14:18,488 - mmseg - INFO - Iter [39950/40000]	lr: 7.650e-08, eta: 0:02:25, time: 2.888, data_time: 0.035, memory: 22371, decode.loss_seg: 0.1006, decode.acc_seg: 88.0206, decode.hr.loss_seg: 0.0143, decode.hr.acc_seg: 88.1527, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.0874, mix.decode.acc_seg: 90.3488, mix.decode.hr.loss_seg: 0.0113, mix.decode.hr.acc_seg: 90.4039, masked.decode.loss_seg: 0.1380, masked.decode.acc_seg: 91.3917, masked.decode.hr.loss_seg: 0.0231, masked.decode.hr.acc_seg: 88.0851
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 500/500, 1.1 task/s, elapsed: 452s, ETA:     0s2023-06-19 01:24:59,256 - mmseg - INFO - per class results:
2023-06-19 01:24:59,257 - mmseg - INFO - 
+---------------+-------+-------+
|     Class     |  IoU  |  Acc  |
+---------------+-------+-------+
|      road     | 96.96 | 98.93 |
|    sidewalk   | 77.87 | 87.97 |
|    building   | 91.44 | 96.48 |
|      wall     | 61.14 | 68.31 |
|     fence     | 51.73 | 60.98 |
|      pole     | 59.01 | 64.47 |
| traffic light | 65.67 |  78.1 |
|  traffic sign | 72.44 | 77.06 |
|   vegetation  | 91.67 | 96.35 |
|    terrain    | 50.95 | 57.63 |
|      sky      | 93.72 | 98.74 |
|     person    | 79.91 | 87.21 |
|     rider     | 55.39 | 76.59 |
|      car      | 94.53 | 96.29 |
|     truck     | 85.63 | 91.15 |
|      bus      | 88.46 | 91.15 |
|     train     | 61.48 | 85.21 |
|   motorcycle  | 65.66 | 80.18 |
|    bicycle    | 68.82 | 79.65 |
+---------------+-------+-------+
2023-06-19 01:24:59,258 - mmseg - INFO - Summary:
2023-06-19 01:24:59,258 - mmseg - INFO - 
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 95.18 | 74.34 | 82.76 |
+-------+-------+-------+
2023-06-19 01:24:59,263 - mmseg - INFO - Saving checkpoint at 40000 iterations
/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:55: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  mem_mb = torch.tensor([mem / (1024 * 1024)],
2023-06-19 01:25:01,556 - mmseg - INFO - Exp name: 230617_1656_gtaHR2csHR_mic_hrda_s2_7894c
2023-06-19 01:25:01,556 - mmseg - INFO - Iter [500/40000]	lr: 1.500e-09, eta: 0:00:00, time: 2.904, data_time: 0.036, memory: 22371, aAcc: 0.9518, mIoU: 0.7434, mAcc: 0.8276, IoU.road: 0.9696, IoU.sidewalk: 0.7787, IoU.building: 0.9144, IoU.wall: 0.6114, IoU.fence: 0.5173, IoU.pole: 0.5901, IoU.traffic light: 0.6567, IoU.traffic sign: 0.7244, IoU.vegetation: 0.9167, IoU.terrain: 0.5095, IoU.sky: 0.9372, IoU.person: 0.7991, IoU.rider: 0.5539, IoU.car: 0.9453, IoU.truck: 0.8563, IoU.bus: 0.8846, IoU.train: 0.6148, IoU.motorcycle: 0.6566, IoU.bicycle: 0.6882, Acc.road: 0.9893, Acc.sidewalk: 0.8797, Acc.building: 0.9648, Acc.wall: 0.6831, Acc.fence: 0.6098, Acc.pole: 0.6447, Acc.traffic light: 0.7810, Acc.traffic sign: 0.7706, Acc.vegetation: 0.9635, Acc.terrain: 0.5763, Acc.sky: 0.9874, Acc.person: 0.8721, Acc.rider: 0.7659, Acc.car: 0.9629, Acc.truck: 0.9115, Acc.bus: 0.9115, Acc.train: 0.8521, Acc.motorcycle: 0.8018, Acc.bicycle: 0.7965, decode.loss_seg: 0.0802, decode.acc_seg: 89.6686, decode.hr.loss_seg: 0.0093, decode.hr.acc_seg: 91.4197, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.0924, mix.decode.acc_seg: 91.6247, mix.decode.hr.loss_seg: 0.0115, mix.decode.hr.acc_seg: 91.5063, masked.decode.loss_seg: 0.1476, masked.decode.acc_seg: 90.4134, masked.decode.hr.loss_seg: 0.0244, masked.decode.hr.acc_seg: 86.8202
```

But, I run agagin, the same python, 
```python
python run_experiments.py --config configs/mic/gtaHR2csHR_mic_hrda.py
```
it occour problem
```txt
ModuleNotFoundError: No module named 'torch._six'
```
Do you know why. 
```txt
seg: 89.8760, mix.decode.hr.loss_seg: 0.0150, mix.decode.hr.acc_seg: 90.4203, masked.decode.loss_seg: 0.1437, masked.decode.acc_seg: 90.9696, masked.decode.hr.loss_seg: 0.0235, masked.decode.hr.acc_seg: 87.6535
/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:55: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  mem_mb = torch.tensor([mem / (1024 * 1024)],
2023-06-19 01:11:54,109 - mmseg - INFO - Iter [39900/40000]	lr: 1.515e-07, eta: 0:04:50, time: 2.899, data_time: 0.036, memory: 22371, decode.loss_seg: 0.0819, decode.acc_seg: 87.3618, decode.hr.loss_seg: 0.0101, decode.hr.acc_seg: 89.3332, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.0927, mix.decode.acc_seg: 89.5286, mix.decode.hr.loss_seg: 0.0105, mix.decode.hr.acc_seg: 91.2364, masked.decode.loss_seg: 0.1427, masked.decode.acc_seg: 91.0264, masked.decode.hr.loss_seg: 0.0224, masked.decode.hr.acc_seg: 88.7455
/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:55: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  mem_mb = torch.tensor([mem / (1024 * 1024)],
2023-06-19 01:14:18,488 - mmseg - INFO - Iter [39950/40000]	lr: 7.650e-08, eta: 0:02:25, time: 2.888, data_time: 0.035, memory: 22371, decode.loss_seg: 0.1006, decode.acc_seg: 88.0206, decode.hr.loss_seg: 0.0143, decode.hr.acc_seg: 88.1527, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.0874, mix.decode.acc_seg: 90.3488, mix.decode.hr.loss_seg: 0.0113, mix.decode.hr.acc_seg: 90.4039, masked.decode.loss_seg: 0.1380, masked.decode.acc_seg: 91.3917, masked.decode.hr.loss_seg: 0.0231, masked.decode.hr.acc_seg: 88.0851
[>>>>>>>>>>>>>>>>>>>>>>>>>>>>>] 500/500, 1.1 task/s, elapsed: 452s, ETA:     0s2023-06-19 01:24:59,256 - mmseg - INFO - per class results:
2023-06-19 01:24:59,257 - mmseg - INFO - 
+---------------+-------+-------+
|     Class     |  IoU  |  Acc  |
+---------------+-------+-------+
|      road     | 96.96 | 98.93 |
|    sidewalk   | 77.87 | 87.97 |
|    building   | 91.44 | 96.48 |
|      wall     | 61.14 | 68.31 |
|     fence     | 51.73 | 60.98 |
|      pole     | 59.01 | 64.47 |
| traffic light | 65.67 |  78.1 |
|  traffic sign | 72.44 | 77.06 |
|   vegetation  | 91.67 | 96.35 |
|    terrain    | 50.95 | 57.63 |
|      sky      | 93.72 | 98.74 |
|     person    | 79.91 | 87.21 |
|     rider     | 55.39 | 76.59 |
|      car      | 94.53 | 96.29 |
|     truck     | 85.63 | 91.15 |
|      bus      | 88.46 | 91.15 |
|     train     | 61.48 | 85.21 |
|   motorcycle  | 65.66 | 80.18 |
|    bicycle    | 68.82 | 79.65 |
+---------------+-------+-------+
2023-06-19 01:24:59,258 - mmseg - INFO - Summary:
2023-06-19 01:24:59,258 - mmseg - INFO - 
+-------+-------+-------+
|  aAcc |  mIoU |  mAcc |
+-------+-------+-------+
| 95.18 | 74.34 | 82.76 |
+-------+-------+-------+
2023-06-19 01:24:59,263 - mmseg - INFO - Saving checkpoint at 40000 iterations
/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/mmcv/runner/hooks/logger/text.py:55: DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
  mem_mb = torch.tensor([mem / (1024 * 1024)],
2023-06-19 01:25:01,556 - mmseg - INFO - Exp name: 230617_1656_gtaHR2csHR_mic_hrda_s2_7894c
2023-06-19 01:25:01,556 - mmseg - INFO - Iter [500/40000]	lr: 1.500e-09, eta: 0:00:00, time: 2.904, data_time: 0.036, memory: 22371, aAcc: 0.9518, mIoU: 0.7434, mAcc: 0.8276, IoU.road: 0.9696, IoU.sidewalk: 0.7787, IoU.building: 0.9144, IoU.wall: 0.6114, IoU.fence: 0.5173, IoU.pole: 0.5901, IoU.traffic light: 0.6567, IoU.traffic sign: 0.7244, IoU.vegetation: 0.9167, IoU.terrain: 0.5095, IoU.sky: 0.9372, IoU.person: 0.7991, IoU.rider: 0.5539, IoU.car: 0.9453, IoU.truck: 0.8563, IoU.bus: 0.8846, IoU.train: 0.6148, IoU.motorcycle: 0.6566, IoU.bicycle: 0.6882, Acc.road: 0.9893, Acc.sidewalk: 0.8797, Acc.building: 0.9648, Acc.wall: 0.6831, Acc.fence: 0.6098, Acc.pole: 0.6447, Acc.traffic light: 0.7810, Acc.traffic sign: 0.7706, Acc.vegetation: 0.9635, Acc.terrain: 0.5763, Acc.sky: 0.9874, Acc.person: 0.8721, Acc.rider: 0.7659, Acc.car: 0.9629, Acc.truck: 0.9115, Acc.bus: 0.9115, Acc.train: 0.8521, Acc.motorcycle: 0.8018, Acc.bicycle: 0.7965, decode.loss_seg: 0.0802, decode.acc_seg: 89.6686, decode.hr.loss_seg: 0.0093, decode.hr.acc_seg: 91.4197, src.loss_imnet_feat_dist: nan, mix.decode.loss_seg: 0.0924, mix.decode.acc_seg: 91.6247, mix.decode.hr.loss_seg: 0.0115, mix.decode.hr.acc_seg: 91.5063, masked.decode.loss_seg: 0.1476, masked.decode.acc_seg: 90.4134, masked.decode.hr.loss_seg: 0.0244, masked.decode.hr.acc_seg: 86.8202
(SMIC) ailab@ailab:/media/ailab/data/yy/S_MIC/MIC/seg$ python run_experiments.py --config configs/mic/gtaHR2csHR_mic_hrda.py
Traceback (most recent call last):
  File "run_experiments.py", line 23, in <module>
    from tools import train
  File "/media/ailab/data/yy/S_MIC/MIC/seg/tools/train.py", line 21, in <module>
    from mmseg.apis import set_random_seed, train_segmentor
  File "/media/ailab/data/yy/S_MIC/MIC/seg/mmseg/apis/__init__.py", line 3, in <module>
    from .inference import inference_segmentor, init_segmentor, show_result_pyplot
  File "/media/ailab/data/yy/S_MIC/MIC/seg/mmseg/apis/inference.py", line 12, in <module>
    from mmseg.models import build_segmentor
  File "/media/ailab/data/yy/S_MIC/MIC/seg/mmseg/models/__init__.py", line 1, in <module>
    from .backbones import *  # noqa: F401,F403
  File "/media/ailab/data/yy/S_MIC/MIC/seg/mmseg/models/backbones/__init__.py", line 4, in <module>
    from .mix_transformer import (MixVisionTransformer, mit_b0, mit_b1, mit_b2,
  File "/media/ailab/data/yy/S_MIC/MIC/seg/mmseg/models/backbones/mix_transformer.py", line 16, in <module>
    from timm.models.layers import DropPath, to_2tuple, trunc_normal_
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint, \
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/__init__.py", line 1, in <module>
    from .cspnet import *
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/cspnet.py", line 20, in <module>
    from .helpers import build_model_with_cfg
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/helpers.py", line 17, in <module>
    from .layers import Conv2dSame, Linear
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/layers/__init__.py", line 7, in <module>
    from .cond_conv2d import CondConv2d, get_condconv_initializer
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/layers/cond_conv2d.py", line 16, in <module>
    from .helpers import to_2tuple
  File "/home/ailab/anaconda3/envs/SMIC/lib/python3.8/site-packages/timm/models/layers/helpers.py", line 6, in <module>
    from torch._six import container_abcs
ModuleNotFoundError: No module named 'torch._six'

```

**Comment by yuheyuan** [comment]
My version conflict, I delete other envirnments. I solve the problem!
